Add article page realisation
gideonazure/phpa_nportal pull request #1
Opened 2020-09-02 13:46 UTC by gideonazure

2020-09-02 16:07 UTC, maxim-kravets requested changes

2020-09-02 16:07 UTC, maxim-kravets commented on src/Controller/ArticleController.php
> +        ]);
Лучше называть шаблон тем же именем, что и у экшна

2020-09-02 16:07 UTC, maxim-kravets commented on src/Service/ArticlePageDataItemFakeProvider.php
> +final class ArticlePageDataItemFakeProvider implements ArticlePageDataProviderInterface
Ощущение что в название класса просто набор слов и не понятно за что он отвечает)
Почему не назвать просто FakeArticleProvider? Тоже самое касается интерфейса

2020-09-02 16:07 UTC, maxim-kravets commented on src/ViewModel/ArticlePageDataItem.php
> +final class ArticlePageDataItem
Тоже набор слов

2020-09-02 16:07 UTC, maxim-kravets commented on src/ViewModel/ArticlePageDataItem.php
> +    private string $articleText;
можно не писать префикс article, и так понятно, что title и text касаются самой статьи

2020-09-02 16:07 UTC, maxim-kravets commented on templates/home/index.html.twig
> +                <a href="/article/{{ latesArticle.id }}">
следует использовать функцию path для генерации ссылки, иначе если вам понадобиться поменять uri, то вы будет менять это по всей разметке

2020-09-02 16:07 UTC, maxim-kravets commented on src/Controller/ArticleController.php
> +        ]);
Необходимо выводить страницу Page Not Found, если статьи с таким id нет

2020-09-02 16:10 UTC, maxim-kravets requested changes

2020-09-02 16:10 UTC, maxim-kravets commented on src/Service/ArticlePageDataItemFakeProvider.php
> +     */
Такие док блоки считаю лишними, так как само название метода говорит о том, что он делает.

2020-09-02 16:10 UTC, maxim-kravets commented on src/Service/ArticlePageDataItemFakeProvider.php
>      public function getItem(int $id): ArticlePageDataItem
Лучше назвать этот метод getById()

2020-09-03 08:10 UTC, gideonazure commented on src/Controller/ArticleController.php
> +        ]);
Внес правки по указанным недочетам. Ошибку можно сейчас сгенерировать, если указать id больше 50 (иного способа вызвать ошибку связанную с id, с учетом генерации данным с помощью Faker, не придумал). Ошибку выбрасывает на стандартной странице 404

2020-09-03 11:33 UTC, maxim-kravets requested changes

2020-09-03 11:33 UTC, maxim-kravets commented on src/Controller/ArticleController.php
> +        }
Некорректно отлавливаете исключение. Если статья не найдена необходимо выводить страницу page not found, а не тот же шаблон, что и для статьи.

2020-09-09 17:36 UTC, merged